name: Frontend-Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure Node caching
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Set up Python 3.11
        uses: actions/setup-python@v5.1.0
        with:
          python-version: "3.11"
      - name: Install python dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install -r requirements.txt
          pip install -r requirements-test.txt
      - name: Install Node dependencies
        working-directory: ./frontend
        run: npm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium
      - name: Build the electron package and webservice
        working-directory: ./frontend
        run: npm run build
      - name: Run tests
        working-directory: ./frontend
        run: npm run test
        timeout-minutes: 2