name: Build & Publish

on:
  push:
    branches:
      - main
jobs:

  release:
    permissions: write-all
    runs-on: ${{ matrix.os }}
    env:
      SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.snapcraft_token }}
    strategy:
      matrix:
        # os: [ubuntu-22.04]
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -r backend/requirements.txt

      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v2
        if: startsWith(matrix.os, 'ubuntu')
      - name: Install dependencies
        working-directory: ./frontend
        run: pnpm install --frozen-lockfile
      - name: Build
        working-directory: ./frontend
        run: pnpm run build
      - name: Publish
        working-directory: ./frontend
        run: pnpm exec electron-builder --publish always
        env:
          GH_TOKEN: ${{ secrets.github_token }}
