name: Build & Publish

on:
  push:
    branches:
      - main
    #  - fix-icon
    # tags:
    #   - "v*"
jobs:

  release:
    permissions: write-all
    runs-on: ${{ matrix.os }}
    env:
      SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.snapcraft_token }}
    strategy:
      matrix:
        # os: [ubuntu-22.04]
        os: [ubuntu-22.04, windows-latest]

    steps:
      - uses: actions/checkout@v4.1.4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5.1.0
        with:
          python-version: "3.11"
      - run: pip install -r backend/requirements.txt
        
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install wheel
      #     pip install -r backend/requirements.txt
      #     pip install -r backend/requirements-dev.txt
      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v2
        if: startsWith(matrix.os, 'ubuntu')
      - name: Build and Publish
        uses: greenmtnboy/action-electron-builder@v1.0.0
        with:
          package_root: frontend
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}
          skip_build: false
          # use_vue_cli: true
          max_attempts: 2

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: true
